# Generated by Django 5.2.8 on 2026-01-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Título del libro')),
                ('cod', models.CharField(max_length=15, unique=True, verbose_name='Codigo')),
                ('author', models.ManyToManyField(to='HolaMundo.author')),
            ],
        ),
    ]
